services:
  db:
    image: pgvector/pgvector:pg17
    container_name: synapse_db
    env_file: ./backend/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: synapse_backend
    env_file: ./backend/.env.dev
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
  
  nginx:
    image: nginx:stable
    container_name: synapse_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend

volumes:
  pgdata:
  static:
  media: